name: Push Docker Images.
on:
    workflow_call:
      inputs:
        image_name:
          description: 'Docker image name'
          required: true
          type: string
        image_tag:
          description: 'Docker image tag'
          required: true
          type: string
  
jobs:
    push-image:
        runs-on: ubuntu-latest

        steps:
            - name: tag docker image.
              run: docker tag ${{ inputs.image_name }}:${{ inputs.image_tag }} anjiofradancy/workflowtest:${{ inputs.image_tag }}
            - name: push docker image
              run: docker push anjiofradancy/workflowtest:${{ inputs.image_tag }}
